# Project : App Name
# Author : MyName
# Date : DD/MM/YYYY
# NOTE : Code Generated by GUIDE [https://github.com/tejxpandit/GUI-Designer-DearPyGUI]

import dearpygui.dearpygui as dpg
from GUIDE import GUIDE

app = GUIDE()

# Project Reference Dictionary {"ID" : "Label"} --> Use Tags
$PROJECTDICT$

# READ DATA
# app.read(ID)

# WRITE DATA
# app.write(ID)

# SHOW COMPONENT
# app.show(ID)

# HIDE COMPONENT
# app.hide(ID)

# BUTTON TRIGGERS

# OTHER TRIGGERS