# Project : App Name
# Author : MyName
# Date : DD/MM/YYYY
# NOTE : Code Generated by GUIDE [https://github.com/tejxpandit/GUI-Designer-DearPyGUI]

import dearpygui.dearpygui as dpg

class GUIDE:
    def __init__(self):
        self.project_name = $PROJECTNAME$
        self.initialize()
        self.createGUI()
        self.runGUI()
        # GUI Variables
        # $PROJECTVARIABLES$

